/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AlopeciaAreataDoctorAtlantaRouteImport } from './routes/alopecia-areata-doctor-atlanta'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlackTrichologistAtlantaRouteImport } from './routes/black-trichologist-atlanta'
import { Route as BookRouteImport } from './routes/book'
import { Route as CccaTreatmentAtlantaRouteImport } from './routes/ccca-treatment-atlanta'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EditorialPolicyRouteImport } from './routes/editorial-policy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FunctionalMedicineRouteImport } from './routes/functional-medicine'
import { Route as HairDoctorAtlantaRouteImport } from './routes/hair-doctor-atlanta'
import { Route as HairLossTreatmentAtlantaRouteImport } from './routes/hair-loss-treatment-atlanta'
import { Route as HairRestorationSandySpringsRouteImport } from './routes/hair-restoration-sandy-springs'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as Landing2RouteImport } from './routes/landing-2'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as MedicalReviewPolicyRouteImport } from './routes/medical-review-policy'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PrpHairTreatmentAtlantaRouteImport } from './routes/prp-hair-treatment-atlanta'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TractionAlopeciaTreatmentAtlantaRouteImport } from './routes/traction-alopecia-treatment-atlanta'
import { Route as TrichologyRouteImport } from './routes/trichology'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSegmentRouteImport } from './routes/blog.$segment'
import { Route as ConcernsIndexRouteImport } from './routes/concerns.index'
import { Route as ConcernsSlugRouteImport } from './routes/concerns.$slug'
import { Route as TreatmentsIndexRouteImport } from './routes/treatments.index'
import { Route as TreatmentsSlugRouteImport } from './routes/treatments.$slug'
import { Route as BlogsHairLossHairLossAndPotassiumDeficiencyWhatSTheRelationshipRouteImport } from './routes/blogs.hair-loss.hair-loss-and-potassium-deficiency-what-s-the-relationship'
import { Route as BlogsHairLossHairLossEpidemicAmongBlackWomenRouteImport } from './routes/blogs.hair-loss.hair-loss-epidemic-among-black-women'
import { Route as BlogsHairLossHowToStopAlopeciaAreataFromGettingWorseRouteImport } from './routes/blogs.hair-loss.how-to-stop-alopecia-areata-from-getting-worse'
import { Route as BlogsHairLossHowToStopAlopeciaAreataFromSpreadingRouteImport } from './routes/blogs.hair-loss.how-to-stop-alopecia-areata-from-spreading'
import { Route as BlogsHairLossMinoxidilItchyScalpKnowTheSurprisingFactsRouteImport } from './routes/blogs.hair-loss.minoxidil-itchy-scalp-know-the-surprising-facts'
import { Route as BlogsHairLossStopHairLossWithDhtBlockersRouteImport } from './routes/blogs.hair-loss.stop-hair-loss-with-dht-blockers'
import { Route as BlogsHairLossThingsToDoBeforeYouGoogleTrichologistNearMeRouteImport } from './routes/blogs.hair-loss.things-to-do-before-you-google-trichologist-near-me'
import { Route as BlogsHairLossTractionAlopeciaWhenIsItTooLateRouteImport } from './routes/blogs.hair-loss.traction-alopecia-when-is-it-too-late'
import { Route as BlogsHairLossTrichologistForBlackHairRouteImport } from './routes/blogs.hair-loss.trichologist-for-black-hair'
import { Route as BlogsHealthWellnessPosts7AmazingAminoAcidsForHairRegrowthYouShouldKnowRouteImport } from './routes/blogs.health-wellness-posts.7-amazing-amino-acids-for-hair-regrowth-you-should-know'
import { Route as BlogsHealthWellnessPostsMagnesiumForHairGrowthRouteImport } from './routes/blogs.health-wellness-posts.magnesium-for-hair-growth'
import { Route as BlogsHealthWellnessPostsMagnesiumHairGrowthRouteImport } from './routes/blogs.health-wellness-posts.magnesium-hair-growth'
import { Route as BlogsHealthWellnessPostsUnlockingTheSecretToRadianceLLysineBenefitsForSkinBeforeAndAfterRouteImport } from './routes/blogs.health-wellness-posts.unlocking-the-secret-to-radiance-l-lysine-benefits-for-skin-before-and-after'
import { Route as ApiPublicSiteImageSplatRouteImport } from './routes/api/public/site-image/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AlopeciaAreataDoctorAtlantaRoute =
  AlopeciaAreataDoctorAtlantaRouteImport.update({
    id: '/alopecia-areata-doctor-atlanta',
    path: '/alopecia-areata-doctor-atlanta',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlackTrichologistAtlantaRoute =
  BlackTrichologistAtlantaRouteImport.update({
    id: '/black-trichologist-atlanta',
    path: '/black-trichologist-atlanta',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const CccaTreatmentAtlantaRoute = CccaTreatmentAtlantaRouteImport.update({
  id: '/ccca-treatment-atlanta',
  path: '/ccca-treatment-atlanta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPolicyRoute = EditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FunctionalMedicineRoute = FunctionalMedicineRouteImport.update({
  id: '/functional-medicine',
  path: '/functional-medicine',
  getParentRoute: () => rootRouteImport,
} as any)
const HairDoctorAtlantaRoute = HairDoctorAtlantaRouteImport.update({
  id: '/hair-doctor-atlanta',
  path: '/hair-doctor-atlanta',
  getParentRoute: () => rootRouteImport,
} as any)
const HairLossTreatmentAtlantaRoute =
  HairLossTreatmentAtlantaRouteImport.update({
    id: '/hair-loss-treatment-atlanta',
    path: '/hair-loss-treatment-atlanta',
    getParentRoute: () => rootRouteImport,
  } as any)
const HairRestorationSandySpringsRoute =
  HairRestorationSandySpringsRouteImport.update({
    id: '/hair-restoration-sandy-springs',
    path: '/hair-restoration-sandy-springs',
    getParentRoute: () => rootRouteImport,
  } as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const Landing2Route = Landing2RouteImport.update({
  id: '/landing-2',
  path: '/landing-2',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalReviewPolicyRoute = MedicalReviewPolicyRouteImport.update({
  id: '/medical-review-policy',
  path: '/medical-review-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrpHairTreatmentAtlantaRoute = PrpHairTreatmentAtlantaRouteImport.update({
  id: '/prp-hair-treatment-atlanta',
  path: '/prp-hair-treatment-atlanta',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TractionAlopeciaTreatmentAtlantaRoute =
  TractionAlopeciaTreatmentAtlantaRouteImport.update({
    id: '/traction-alopecia-treatment-atlanta',
    path: '/traction-alopecia-treatment-atlanta',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrichologyRoute = TrichologyRouteImport.update({
  id: '/trichology',
  path: '/trichology',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSegmentRoute = BlogSegmentRouteImport.update({
  id: '/blog/$segment',
  path: '/blog/$segment',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcernsIndexRoute = ConcernsIndexRouteImport.update({
  id: '/concerns/',
  path: '/concerns/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcernsSlugRoute = ConcernsSlugRouteImport.update({
  id: '/concerns/$slug',
  path: '/concerns/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsIndexRoute = TreatmentsIndexRouteImport.update({
  id: '/treatments/',
  path: '/treatments/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsSlugRoute = TreatmentsSlugRouteImport.update({
  id: '/treatments/$slug',
  path: '/treatments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsHairLossHairLossAndPotassiumDeficiencyWhatSTheRelationshipRoute =
  BlogsHairLossHairLossAndPotassiumDeficiencyWhatSTheRelationshipRouteImport.update(
    {
      id: '/blogs/hair-loss/hair-loss-and-potassium-deficiency-what-s-the-relationship',
      path: '/blogs/hair-loss/hair-loss-and-potassium-deficiency-what-s-the-relationship',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const BlogsHairLossHairLossEpidemicAmongBlackWomenRoute =
  BlogsHairLossHairLossEpidemicAmongBlackWomenRouteImport.update({
    id: '/blogs/hair-loss/hair-loss-epidemic-among-black-women',
    path: '/blogs/hair-loss/hair-loss-epidemic-among-black-women',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogsHairLossHowToStopAlopeciaAreataFromGettingWorseRoute =
  BlogsHairLossHowToStopAlopeciaAreataFromGettingWorseRouteImport.update({
    id: '/blogs/hair-loss/how-to-stop-alopecia-areata-from-getting-worse',
    path: '/blogs/hair-loss/how-to-stop-alopecia-areata-from-getting-worse',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogsHairLossHowToStopAlopeciaAreataFromSpreadingRoute =
  BlogsHairLossHowToStopAlopeciaAreataFromSpreadingRouteImport.update({
    id: '/blogs/hair-loss/how-to-stop-alopecia-areata-from-spreading',
    path: '/blogs/hair-loss/how-to-stop-alopecia-areata-from-spreading',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogsHairLossMinoxidilItchyScalpKnowTheSurprisingFactsRoute =
  BlogsHairLossMinoxidilItchyScalpKnowTheSurprisingFactsRouteImport.update({
    id: '/blogs/hair-loss/minoxidil-itchy-scalp-know-the-surprising-facts',
    path: '/blogs/hair-loss/minoxidil-itchy-scalp-know-the-surprising-facts',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogsHairLossStopHairLossWithDhtBlockersRoute =
  BlogsHairLossStopHairLossWithDhtBlockersRouteImport.update({
    id: '/blogs/hair-loss/stop-hair-loss-with-dht-blockers',
    path: '/blogs/hair-loss/stop-hair-loss-with-dht-blockers',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogsHairLossThingsToDoBeforeYouGoogleTrichologistNearMeRoute =
  BlogsHairLossThingsToDoBeforeYouGoogleTrichologistNearMeRouteImport.update({
    id: '/blogs/hair-loss/things-to-do-before-you-google-trichologist-near-me',
    path: '/blogs/hair-loss/things-to-do-before-you-google-trichologist-near-me',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogsHairLossTractionAlopeciaWhenIsItTooLateRoute =
  BlogsHairLossTractionAlopeciaWhenIsItTooLateRouteImport.update({
    id: '/blogs/hair-loss/traction-alopecia-when-is-it-too-late',
    path: '/blogs/hair-loss/traction-alopecia-when-is-it-too-late',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogsHairLossTrichologistForBlackHairRoute =
  BlogsHairLossTrichologistForBlackHairRouteImport.update({
    id: '/blogs/hair-loss/trichologist-for-black-hair',
    path: '/blogs/hair-loss/trichologist-for-black-hair',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogsHealthWellnessPosts7AmazingAminoAcidsForHairRegrowthYouShouldKnowRoute =
  BlogsHealthWellnessPosts7AmazingAminoAcidsForHairRegrowthYouShouldKnowRouteImport.update(
    {
      id: '/blogs/health-wellness-posts/7-amazing-amino-acids-for-hair-regrowth-you-should-know',
      path: '/blogs/health-wellness-posts/7-amazing-amino-acids-for-hair-regrowth-you-should-know',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const BlogsHealthWellnessPostsMagnesiumForHairGrowthRoute =
  BlogsHealthWellnessPostsMagnesiumForHairGrowthRouteImport.update({
    id: '/blogs/health-wellness-posts/magnesium-for-hair-growth',
    path: '/blogs/health-wellness-posts/magnesium-for-hair-growth',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogsHealthWellnessPostsMagnesiumHairGrowthRoute =
  BlogsHealthWellnessPostsMagnesiumHairGrowthRouteImport.update({
    id: '/blogs/health-wellness-posts/magnesium-hair-growth',
    path: '/blogs/health-wellness-posts/magnesium-hair-growth',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogsHealthWellnessPostsUnlockingTheSecretToRadianceLLysineBenefitsForSkinBeforeAndAfterRoute =
  BlogsHealthWellnessPostsUnlockingTheSecretToRadianceLLysineBenefitsForSkinBeforeAndAfterRouteImport.update(
    {
      id: '/blogs/health-wellness-posts/unlocking-the-secret-to-radiance-l-lysine-benefits-for-skin-before-and-after',
      path: '/blogs/health-wellness-posts/unlocking-the-secret-to-radiance-l-lysine-benefits-for-skin-before-and-after',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const ApiPublicSiteImageSplatRoute = ApiPublicSiteImageSplatRouteImport.update({
  id: '/api/public/site-image/$',
  path: '/api/public/site-image/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alopecia-areata-doctor-atlanta': typeof AlopeciaAreataDoctorAtlantaRoute
  '/auth': typeof AuthRoute
  '/black-trichologist-atlanta': typeof BlackTrichologistAtlantaRoute
  '/book': typeof BookRoute
  '/ccca-treatment-atlanta': typeof CccaTreatmentAtlantaRoute
  '/contact': typeof ContactRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/faq': typeof FaqRoute
  '/functional-medicine': typeof FunctionalMedicineRoute
  '/hair-doctor-atlanta': typeof HairDoctorAtlantaRoute
  '/hair-loss-treatment-atlanta': typeof HairLossTreatmentAtlantaRoute
  '/hair-restoration-sandy-springs': typeof HairRestorationSandySpringsRoute
  '/landing': typeof LandingRoute
  '/landing-2': typeof Landing2Route
  '/llms.txt': typeof LlmsDottxtRoute
  '/medical-review-policy': typeof MedicalReviewPolicyRoute
  '/policies': typeof PoliciesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/prp-hair-treatment-atlanta': typeof PrpHairTreatmentAtlantaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/traction-alopecia-treatment-atlanta': typeof TractionAlopeciaTreatmentAtlantaRoute
  '/trichology': typeof TrichologyRoute
  '/videos': typeof VideosRoute
  '/blog/$segment': typeof BlogSegmentRoute
  '/concerns/$slug': typeof ConcernsSlugRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/concerns/': typeof ConcernsIndexRoute
  '/treatments/': typeof TreatmentsIndexRoute
  '/blogs/hair-loss/hair-loss-and-potassium-deficiency-what-s-the-relationship': typeof BlogsHairLossHairLossAndPotassiumDeficiencyWhatSTheRelationshipRoute
  '/blogs/hair-loss/hair-loss-epidemic-among-black-women': typeof BlogsHairLossHairLossEpidemicAmongBlackWomenRoute
  '/blogs/hair-loss/how-to-stop-alopecia-areata-from-getting-worse': typeof BlogsHairLossHowToStopAlopeciaAreataFromGettingWorseRoute
  '/blogs/hair-loss/how-to-stop-alopecia-areata-from-spreading': typeof BlogsHairLossHowToStopAlopeciaAreataFromSpreadingRoute
  '/blogs/hair-loss/minoxidil-itchy-scalp-know-the-surprising-facts': typeof BlogsHairLossMinoxidilItchyScalpKnowTheSurprisingFactsRoute
  '/blogs/hair-loss/stop-hair-loss-with-dht-blockers': typeof BlogsHairLossStopHairLossWithDhtBlockersRoute
  '/blogs/hair-loss/things-to-do-before-you-google-trichologist-near-me': typeof BlogsHairLossThingsToDoBeforeYouGoogleTrichologistNearMeRoute
  '/blogs/hair-loss/traction-alopecia-when-is-it-too-late': typeof BlogsHairLossTractionAlopeciaWhenIsItTooLateRoute
  '/blogs/hair-loss/trichologist-for-black-hair': typeof BlogsHairLossTrichologistForBlackHairRoute
  '/blogs/health-wellness-posts/7-amazing-amino-acids-for-hair-regrowth-you-should-know': typeof BlogsHealthWellnessPosts7AmazingAminoAcidsForHairRegrowthYouShouldKnowRoute
  '/blogs/health-wellness-posts/magnesium-for-hair-growth': typeof BlogsHealthWellnessPostsMagnesiumForHairGrowthRoute
  '/blogs/health-wellness-posts/magnesium-hair-growth': typeof BlogsHealthWellnessPostsMagnesiumHairGrowthRoute
  '/blogs/health-wellness-posts/unlocking-the-secret-to-radiance-l-lysine-benefits-for-skin-before-and-after': typeof BlogsHealthWellnessPostsUnlockingTheSecretToRadianceLLysineBenefitsForSkinBeforeAndAfterRoute
  '/api/public/site-image/$': typeof ApiPublicSiteImageSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alopecia-areata-doctor-atlanta': typeof AlopeciaAreataDoctorAtlantaRoute
  '/auth': typeof AuthRoute
  '/black-trichologist-atlanta': typeof BlackTrichologistAtlantaRoute
  '/book': typeof BookRoute
  '/ccca-treatment-atlanta': typeof CccaTreatmentAtlantaRoute
  '/contact': typeof ContactRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/faq': typeof FaqRoute
  '/functional-medicine': typeof FunctionalMedicineRoute
  '/hair-doctor-atlanta': typeof HairDoctorAtlantaRoute
  '/hair-loss-treatment-atlanta': typeof HairLossTreatmentAtlantaRoute
  '/hair-restoration-sandy-springs': typeof HairRestorationSandySpringsRoute
  '/landing': typeof LandingRoute
  '/landing-2': typeof Landing2Route
  '/llms.txt': typeof LlmsDottxtRoute
  '/medical-review-policy': typeof MedicalReviewPolicyRoute
  '/policies': typeof PoliciesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/prp-hair-treatment-atlanta': typeof PrpHairTreatmentAtlantaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/traction-alopecia-treatment-atlanta': typeof TractionAlopeciaTreatmentAtlantaRoute
  '/trichology': typeof TrichologyRoute
  '/videos': typeof VideosRoute
  '/blog/$segment': typeof BlogSegmentRoute
  '/concerns/$slug': typeof ConcernsSlugRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/concerns': typeof ConcernsIndexRoute
  '/treatments': typeof TreatmentsIndexRoute
  '/blogs/hair-loss/hair-loss-and-potassium-deficiency-what-s-the-relationship': typeof BlogsHairLossHairLossAndPotassiumDeficiencyWhatSTheRelationshipRoute
  '/blogs/hair-loss/hair-loss-epidemic-among-black-women': typeof BlogsHairLossHairLossEpidemicAmongBlackWomenRoute
  '/blogs/hair-loss/how-to-stop-alopecia-areata-from-getting-worse': typeof BlogsHairLossHowToStopAlopeciaAreataFromGettingWorseRoute
  '/blogs/hair-loss/how-to-stop-alopecia-areata-from-spreading': typeof BlogsHairLossHowToStopAlopeciaAreataFromSpreadingRoute
  '/blogs/hair-loss/minoxidil-itchy-scalp-know-the-surprising-facts': typeof BlogsHairLossMinoxidilItchyScalpKnowTheSurprisingFactsRoute
  '/blogs/hair-loss/stop-hair-loss-with-dht-blockers': typeof BlogsHairLossStopHairLossWithDhtBlockersRoute
  '/blogs/hair-loss/things-to-do-before-you-google-trichologist-near-me': typeof BlogsHairLossThingsToDoBeforeYouGoogleTrichologistNearMeRoute
  '/blogs/hair-loss/traction-alopecia-when-is-it-too-late': typeof BlogsHairLossTractionAlopeciaWhenIsItTooLateRoute
  '/blogs/hair-loss/trichologist-for-black-hair': typeof BlogsHairLossTrichologistForBlackHairRoute
  '/blogs/health-wellness-posts/7-amazing-amino-acids-for-hair-regrowth-you-should-know': typeof BlogsHealthWellnessPosts7AmazingAminoAcidsForHairRegrowthYouShouldKnowRoute
  '/blogs/health-wellness-posts/magnesium-for-hair-growth': typeof BlogsHealthWellnessPostsMagnesiumForHairGrowthRoute
  '/blogs/health-wellness-posts/magnesium-hair-growth': typeof BlogsHealthWellnessPostsMagnesiumHairGrowthRoute
  '/blogs/health-wellness-posts/unlocking-the-secret-to-radiance-l-lysine-benefits-for-skin-before-and-after': typeof BlogsHealthWellnessPostsUnlockingTheSecretToRadianceLLysineBenefitsForSkinBeforeAndAfterRoute
  '/api/public/site-image/$': typeof ApiPublicSiteImageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alopecia-areata-doctor-atlanta': typeof AlopeciaAreataDoctorAtlantaRoute
  '/auth': typeof AuthRoute
  '/black-trichologist-atlanta': typeof BlackTrichologistAtlantaRoute
  '/book': typeof BookRoute
  '/ccca-treatment-atlanta': typeof CccaTreatmentAtlantaRoute
  '/contact': typeof ContactRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/faq': typeof FaqRoute
  '/functional-medicine': typeof FunctionalMedicineRoute
  '/hair-doctor-atlanta': typeof HairDoctorAtlantaRoute
  '/hair-loss-treatment-atlanta': typeof HairLossTreatmentAtlantaRoute
  '/hair-restoration-sandy-springs': typeof HairRestorationSandySpringsRoute
  '/landing': typeof LandingRoute
  '/landing-2': typeof Landing2Route
  '/llms.txt': typeof LlmsDottxtRoute
  '/medical-review-policy': typeof MedicalReviewPolicyRoute
  '/policies': typeof PoliciesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/prp-hair-treatment-atlanta': typeof PrpHairTreatmentAtlantaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/traction-alopecia-treatment-atlanta': typeof TractionAlopeciaTreatmentAtlantaRoute
  '/trichology': typeof TrichologyRoute
  '/videos': typeof VideosRoute
  '/blog/$segment': typeof BlogSegmentRoute
  '/concerns/$slug': typeof ConcernsSlugRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/concerns/': typeof ConcernsIndexRoute
  '/treatments/': typeof TreatmentsIndexRoute
  '/blogs/hair-loss/hair-loss-and-potassium-deficiency-what-s-the-relationship': typeof BlogsHairLossHairLossAndPotassiumDeficiencyWhatSTheRelationshipRoute
  '/blogs/hair-loss/hair-loss-epidemic-among-black-women': typeof BlogsHairLossHairLossEpidemicAmongBlackWomenRoute
  '/blogs/hair-loss/how-to-stop-alopecia-areata-from-getting-worse': typeof BlogsHairLossHowToStopAlopeciaAreataFromGettingWorseRoute
  '/blogs/hair-loss/how-to-stop-alopecia-areata-from-spreading': typeof BlogsHairLossHowToStopAlopeciaAreataFromSpreadingRoute
  '/blogs/hair-loss/minoxidil-itchy-scalp-know-the-surprising-facts': typeof BlogsHairLossMinoxidilItchyScalpKnowTheSurprisingFactsRoute
  '/blogs/hair-loss/stop-hair-loss-with-dht-blockers': typeof BlogsHairLossStopHairLossWithDhtBlockersRoute
  '/blogs/hair-loss/things-to-do-before-you-google-trichologist-near-me': typeof BlogsHairLossThingsToDoBeforeYouGoogleTrichologistNearMeRoute
  '/blogs/hair-loss/traction-alopecia-when-is-it-too-late': typeof BlogsHairLossTractionAlopeciaWhenIsItTooLateRoute
  '/blogs/hair-loss/trichologist-for-black-hair': typeof BlogsHairLossTrichologistForBlackHairRoute
  '/blogs/health-wellness-posts/7-amazing-amino-acids-for-hair-regrowth-you-should-know': typeof BlogsHealthWellnessPosts7AmazingAminoAcidsForHairRegrowthYouShouldKnowRoute
  '/blogs/health-wellness-posts/magnesium-for-hair-growth': typeof BlogsHealthWellnessPostsMagnesiumForHairGrowthRoute
  '/blogs/health-wellness-posts/magnesium-hair-growth': typeof BlogsHealthWellnessPostsMagnesiumHairGrowthRoute
  '/blogs/health-wellness-posts/unlocking-the-secret-to-radiance-l-lysine-benefits-for-skin-before-and-after': typeof BlogsHealthWellnessPostsUnlockingTheSecretToRadianceLLysineBenefitsForSkinBeforeAndAfterRoute
  '/api/public/site-image/$': typeof ApiPublicSiteImageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/alopecia-areata-doctor-atlanta'
    | '/auth'
    | '/black-trichologist-atlanta'
    | '/book'
    | '/ccca-treatment-atlanta'
    | '/contact'
    | '/editorial-policy'
    | '/faq'
    | '/functional-medicine'
    | '/hair-doctor-atlanta'
    | '/hair-loss-treatment-atlanta'
    | '/hair-restoration-sandy-springs'
    | '/landing'
    | '/landing-2'
    | '/llms.txt'
    | '/medical-review-policy'
    | '/policies'
    | '/privacy-policy'
    | '/prp-hair-treatment-atlanta'
    | '/sitemap.xml'
    | '/traction-alopecia-treatment-atlanta'
    | '/trichology'
    | '/videos'
    | '/blog/$segment'
    | '/concerns/$slug'
    | '/treatments/$slug'
    | '/blog/'
    | '/concerns/'
    | '/treatments/'
    | '/blogs/hair-loss/hair-loss-and-potassium-deficiency-what-s-the-relationship'
    | '/blogs/hair-loss/hair-loss-epidemic-among-black-women'
    | '/blogs/hair-loss/how-to-stop-alopecia-areata-from-getting-worse'
    | '/blogs/hair-loss/how-to-stop-alopecia-areata-from-spreading'
    | '/blogs/hair-loss/minoxidil-itchy-scalp-know-the-surprising-facts'
    | '/blogs/hair-loss/stop-hair-loss-with-dht-blockers'
    | '/blogs/hair-loss/things-to-do-before-you-google-trichologist-near-me'
    | '/blogs/hair-loss/traction-alopecia-when-is-it-too-late'
    | '/blogs/hair-loss/trichologist-for-black-hair'
    | '/blogs/health-wellness-posts/7-amazing-amino-acids-for-hair-regrowth-you-should-know'
    | '/blogs/health-wellness-posts/magnesium-for-hair-growth'
    | '/blogs/health-wellness-posts/magnesium-hair-growth'
    | '/blogs/health-wellness-posts/unlocking-the-secret-to-radiance-l-lysine-benefits-for-skin-before-and-after'
    | '/api/public/site-image/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/alopecia-areata-doctor-atlanta'
    | '/auth'
    | '/black-trichologist-atlanta'
    | '/book'
    | '/ccca-treatment-atlanta'
    | '/contact'
    | '/editorial-policy'
    | '/faq'
    | '/functional-medicine'
    | '/hair-doctor-atlanta'
    | '/hair-loss-treatment-atlanta'
    | '/hair-restoration-sandy-springs'
    | '/landing'
    | '/landing-2'
    | '/llms.txt'
    | '/medical-review-policy'
    | '/policies'
    | '/privacy-policy'
    | '/prp-hair-treatment-atlanta'
    | '/sitemap.xml'
    | '/traction-alopecia-treatment-atlanta'
    | '/trichology'
    | '/videos'
    | '/blog/$segment'
    | '/concerns/$slug'
    | '/treatments/$slug'
    | '/blog'
    | '/concerns'
    | '/treatments'
    | '/blogs/hair-loss/hair-loss-and-potassium-deficiency-what-s-the-relationship'
    | '/blogs/hair-loss/hair-loss-epidemic-among-black-women'
    | '/blogs/hair-loss/how-to-stop-alopecia-areata-from-getting-worse'
    | '/blogs/hair-loss/how-to-stop-alopecia-areata-from-spreading'
    | '/blogs/hair-loss/minoxidil-itchy-scalp-know-the-surprising-facts'
    | '/blogs/hair-loss/stop-hair-loss-with-dht-blockers'
    | '/blogs/hair-loss/things-to-do-before-you-google-trichologist-near-me'
    | '/blogs/hair-loss/traction-alopecia-when-is-it-too-late'
    | '/blogs/hair-loss/trichologist-for-black-hair'
    | '/blogs/health-wellness-posts/7-amazing-amino-acids-for-hair-regrowth-you-should-know'
    | '/blogs/health-wellness-posts/magnesium-for-hair-growth'
    | '/blogs/health-wellness-posts/magnesium-hair-growth'
    | '/blogs/health-wellness-posts/unlocking-the-secret-to-radiance-l-lysine-benefits-for-skin-before-and-after'
    | '/api/public/site-image/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/alopecia-areata-doctor-atlanta'
    | '/auth'
    | '/black-trichologist-atlanta'
    | '/book'
    | '/ccca-treatment-atlanta'
    | '/contact'
    | '/editorial-policy'
    | '/faq'
    | '/functional-medicine'
    | '/hair-doctor-atlanta'
    | '/hair-loss-treatment-atlanta'
    | '/hair-restoration-sandy-springs'
    | '/landing'
    | '/landing-2'
    | '/llms.txt'
    | '/medical-review-policy'
    | '/policies'
    | '/privacy-policy'
    | '/prp-hair-treatment-atlanta'
    | '/sitemap.xml'
    | '/traction-alopecia-treatment-atlanta'
    | '/trichology'
    | '/videos'
    | '/blog/$segment'
    | '/concerns/$slug'
    | '/treatments/$slug'
    | '/blog/'
    | '/concerns/'
    | '/treatments/'
    | '/blogs/hair-loss/hair-loss-and-potassium-deficiency-what-s-the-relationship'
    | '/blogs/hair-loss/hair-loss-epidemic-among-black-women'
    | '/blogs/hair-loss/how-to-stop-alopecia-areata-from-getting-worse'
    | '/blogs/hair-loss/how-to-stop-alopecia-areata-from-spreading'
    | '/blogs/hair-loss/minoxidil-itchy-scalp-know-the-surprising-facts'
    | '/blogs/hair-loss/stop-hair-loss-with-dht-blockers'
    | '/blogs/hair-loss/things-to-do-before-you-google-trichologist-near-me'
    | '/blogs/hair-loss/traction-alopecia-when-is-it-too-late'
    | '/blogs/hair-loss/trichologist-for-black-hair'
    | '/blogs/health-wellness-posts/7-amazing-amino-acids-for-hair-regrowth-you-should-know'
    | '/blogs/health-wellness-posts/magnesium-for-hair-growth'
    | '/blogs/health-wellness-posts/magnesium-hair-growth'
    | '/blogs/health-wellness-posts/unlocking-the-secret-to-radiance-l-lysine-benefits-for-skin-before-and-after'
    | '/api/public/site-image/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AlopeciaAreataDoctorAtlantaRoute: typeof AlopeciaAreataDoctorAtlantaRoute
  AuthRoute: typeof AuthRoute
  BlackTrichologistAtlantaRoute: typeof BlackTrichologistAtlantaRoute
  BookRoute: typeof BookRoute
  CccaTreatmentAtlantaRoute: typeof CccaTreatmentAtlantaRoute
  ContactRoute: typeof ContactRoute
  EditorialPolicyRoute: typeof EditorialPolicyRoute
  FaqRoute: typeof FaqRoute
  FunctionalMedicineRoute: typeof FunctionalMedicineRoute
  HairDoctorAtlantaRoute: typeof HairDoctorAtlantaRoute
  HairLossTreatmentAtlantaRoute: typeof HairLossTreatmentAtlantaRoute
  HairRestorationSandySpringsRoute: typeof HairRestorationSandySpringsRoute
  LandingRoute: typeof LandingRoute
  Landing2Route: typeof Landing2Route
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  MedicalReviewPolicyRoute: typeof MedicalReviewPolicyRoute
  PoliciesRoute: typeof PoliciesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PrpHairTreatmentAtlantaRoute: typeof PrpHairTreatmentAtlantaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TractionAlopeciaTreatmentAtlantaRoute: typeof TractionAlopeciaTreatmentAtlantaRoute
  TrichologyRoute: typeof TrichologyRoute
  VideosRoute: typeof VideosRoute
  BlogSegmentRoute: typeof BlogSegmentRoute
  ConcernsSlugRoute: typeof ConcernsSlugRoute
  TreatmentsSlugRoute: typeof TreatmentsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ConcernsIndexRoute: typeof ConcernsIndexRoute
  TreatmentsIndexRoute: typeof TreatmentsIndexRoute
  BlogsHairLossHairLossAndPotassiumDeficiencyWhatSTheRelationshipRoute: typeof BlogsHairLossHairLossAndPotassiumDeficiencyWhatSTheRelationshipRoute
  BlogsHairLossHairLossEpidemicAmongBlackWomenRoute: typeof BlogsHairLossHairLossEpidemicAmongBlackWomenRoute
  BlogsHairLossHowToStopAlopeciaAreataFromGettingWorseRoute: typeof BlogsHairLossHowToStopAlopeciaAreataFromGettingWorseRoute
  BlogsHairLossHowToStopAlopeciaAreataFromSpreadingRoute: typeof BlogsHairLossHowToStopAlopeciaAreataFromSpreadingRoute
  BlogsHairLossMinoxidilItchyScalpKnowTheSurprisingFactsRoute: typeof BlogsHairLossMinoxidilItchyScalpKnowTheSurprisingFactsRoute
  BlogsHairLossStopHairLossWithDhtBlockersRoute: typeof BlogsHairLossStopHairLossWithDhtBlockersRoute
  BlogsHairLossThingsToDoBeforeYouGoogleTrichologistNearMeRoute: typeof BlogsHairLossThingsToDoBeforeYouGoogleTrichologistNearMeRoute
  BlogsHairLossTractionAlopeciaWhenIsItTooLateRoute: typeof BlogsHairLossTractionAlopeciaWhenIsItTooLateRoute
  BlogsHairLossTrichologistForBlackHairRoute: typeof BlogsHairLossTrichologistForBlackHairRoute
  BlogsHealthWellnessPosts7AmazingAminoAcidsForHairRegrowthYouShouldKnowRoute: typeof BlogsHealthWellnessPosts7AmazingAminoAcidsForHairRegrowthYouShouldKnowRoute
  BlogsHealthWellnessPostsMagnesiumForHairGrowthRoute: typeof BlogsHealthWellnessPostsMagnesiumForHairGrowthRoute
  BlogsHealthWellnessPostsMagnesiumHairGrowthRoute: typeof BlogsHealthWellnessPostsMagnesiumHairGrowthRoute
  BlogsHealthWellnessPostsUnlockingTheSecretToRadianceLLysineBenefitsForSkinBeforeAndAfterRoute: typeof BlogsHealthWellnessPostsUnlockingTheSecretToRadianceLLysineBenefitsForSkinBeforeAndAfterRoute
  ApiPublicSiteImageSplatRoute: typeof ApiPublicSiteImageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alopecia-areata-doctor-atlanta': {
      id: '/alopecia-areata-doctor-atlanta'
      path: '/alopecia-areata-doctor-atlanta'
      fullPath: '/alopecia-areata-doctor-atlanta'
      preLoaderRoute: typeof AlopeciaAreataDoctorAtlantaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/black-trichologist-atlanta': {
      id: '/black-trichologist-atlanta'
      path: '/black-trichologist-atlanta'
      fullPath: '/black-trichologist-atlanta'
      preLoaderRoute: typeof BlackTrichologistAtlantaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ccca-treatment-atlanta': {
      id: '/ccca-treatment-atlanta'
      path: '/ccca-treatment-atlanta'
      fullPath: '/ccca-treatment-atlanta'
      preLoaderRoute: typeof CccaTreatmentAtlantaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-policy': {
      id: '/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/editorial-policy'
      preLoaderRoute: typeof EditorialPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/functional-medicine': {
      id: '/functional-medicine'
      path: '/functional-medicine'
      fullPath: '/functional-medicine'
      preLoaderRoute: typeof FunctionalMedicineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hair-doctor-atlanta': {
      id: '/hair-doctor-atlanta'
      path: '/hair-doctor-atlanta'
      fullPath: '/hair-doctor-atlanta'
      preLoaderRoute: typeof HairDoctorAtlantaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hair-loss-treatment-atlanta': {
      id: '/hair-loss-treatment-atlanta'
      path: '/hair-loss-treatment-atlanta'
      fullPath: '/hair-loss-treatment-atlanta'
      preLoaderRoute: typeof HairLossTreatmentAtlantaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hair-restoration-sandy-springs': {
      id: '/hair-restoration-sandy-springs'
      path: '/hair-restoration-sandy-springs'
      fullPath: '/hair-restoration-sandy-springs'
      preLoaderRoute: typeof HairRestorationSandySpringsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-2': {
      id: '/landing-2'
      path: '/landing-2'
      fullPath: '/landing-2'
      preLoaderRoute: typeof Landing2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-review-policy': {
      id: '/medical-review-policy'
      path: '/medical-review-policy'
      fullPath: '/medical-review-policy'
      preLoaderRoute: typeof MedicalReviewPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prp-hair-treatment-atlanta': {
      id: '/prp-hair-treatment-atlanta'
      path: '/prp-hair-treatment-atlanta'
      fullPath: '/prp-hair-treatment-atlanta'
      preLoaderRoute: typeof PrpHairTreatmentAtlantaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traction-alopecia-treatment-atlanta': {
      id: '/traction-alopecia-treatment-atlanta'
      path: '/traction-alopecia-treatment-atlanta'
      fullPath: '/traction-alopecia-treatment-atlanta'
      preLoaderRoute: typeof TractionAlopeciaTreatmentAtlantaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trichology': {
      id: '/trichology'
      path: '/trichology'
      fullPath: '/trichology'
      preLoaderRoute: typeof TrichologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$segment': {
      id: '/blog/$segment'
      path: '/blog/$segment'
      fullPath: '/blog/$segment'
      preLoaderRoute: typeof BlogSegmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concerns/': {
      id: '/concerns/'
      path: '/concerns'
      fullPath: '/concerns/'
      preLoaderRoute: typeof ConcernsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concerns/$slug': {
      id: '/concerns/$slug'
      path: '/concerns/$slug'
      fullPath: '/concerns/$slug'
      preLoaderRoute: typeof ConcernsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/': {
      id: '/treatments/'
      path: '/treatments'
      fullPath: '/treatments/'
      preLoaderRoute: typeof TreatmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/$slug': {
      id: '/treatments/$slug'
      path: '/treatments/$slug'
      fullPath: '/treatments/$slug'
      preLoaderRoute: typeof TreatmentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/hair-loss/hair-loss-and-potassium-deficiency-what-s-the-relationship': {
      id: '/blogs/hair-loss/hair-loss-and-potassium-deficiency-what-s-the-relationship'
      path: '/blogs/hair-loss/hair-loss-and-potassium-deficiency-what-s-the-relationship'
      fullPath: '/blogs/hair-loss/hair-loss-and-potassium-deficiency-what-s-the-relationship'
      preLoaderRoute: typeof BlogsHairLossHairLossAndPotassiumDeficiencyWhatSTheRelationshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/hair-loss/hair-loss-epidemic-among-black-women': {
      id: '/blogs/hair-loss/hair-loss-epidemic-among-black-women'
      path: '/blogs/hair-loss/hair-loss-epidemic-among-black-women'
      fullPath: '/blogs/hair-loss/hair-loss-epidemic-among-black-women'
      preLoaderRoute: typeof BlogsHairLossHairLossEpidemicAmongBlackWomenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/hair-loss/how-to-stop-alopecia-areata-from-getting-worse': {
      id: '/blogs/hair-loss/how-to-stop-alopecia-areata-from-getting-worse'
      path: '/blogs/hair-loss/how-to-stop-alopecia-areata-from-getting-worse'
      fullPath: '/blogs/hair-loss/how-to-stop-alopecia-areata-from-getting-worse'
      preLoaderRoute: typeof BlogsHairLossHowToStopAlopeciaAreataFromGettingWorseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/hair-loss/how-to-stop-alopecia-areata-from-spreading': {
      id: '/blogs/hair-loss/how-to-stop-alopecia-areata-from-spreading'
      path: '/blogs/hair-loss/how-to-stop-alopecia-areata-from-spreading'
      fullPath: '/blogs/hair-loss/how-to-stop-alopecia-areata-from-spreading'
      preLoaderRoute: typeof BlogsHairLossHowToStopAlopeciaAreataFromSpreadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/hair-loss/minoxidil-itchy-scalp-know-the-surprising-facts': {
      id: '/blogs/hair-loss/minoxidil-itchy-scalp-know-the-surprising-facts'
      path: '/blogs/hair-loss/minoxidil-itchy-scalp-know-the-surprising-facts'
      fullPath: '/blogs/hair-loss/minoxidil-itchy-scalp-know-the-surprising-facts'
      preLoaderRoute: typeof BlogsHairLossMinoxidilItchyScalpKnowTheSurprisingFactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/hair-loss/stop-hair-loss-with-dht-blockers': {
      id: '/blogs/hair-loss/stop-hair-loss-with-dht-blockers'
      path: '/blogs/hair-loss/stop-hair-loss-with-dht-blockers'
      fullPath: '/blogs/hair-loss/stop-hair-loss-with-dht-blockers'
      preLoaderRoute: typeof BlogsHairLossStopHairLossWithDhtBlockersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/hair-loss/things-to-do-before-you-google-trichologist-near-me': {
      id: '/blogs/hair-loss/things-to-do-before-you-google-trichologist-near-me'
      path: '/blogs/hair-loss/things-to-do-before-you-google-trichologist-near-me'
      fullPath: '/blogs/hair-loss/things-to-do-before-you-google-trichologist-near-me'
      preLoaderRoute: typeof BlogsHairLossThingsToDoBeforeYouGoogleTrichologistNearMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/hair-loss/traction-alopecia-when-is-it-too-late': {
      id: '/blogs/hair-loss/traction-alopecia-when-is-it-too-late'
      path: '/blogs/hair-loss/traction-alopecia-when-is-it-too-late'
      fullPath: '/blogs/hair-loss/traction-alopecia-when-is-it-too-late'
      preLoaderRoute: typeof BlogsHairLossTractionAlopeciaWhenIsItTooLateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/hair-loss/trichologist-for-black-hair': {
      id: '/blogs/hair-loss/trichologist-for-black-hair'
      path: '/blogs/hair-loss/trichologist-for-black-hair'
      fullPath: '/blogs/hair-loss/trichologist-for-black-hair'
      preLoaderRoute: typeof BlogsHairLossTrichologistForBlackHairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/health-wellness-posts/7-amazing-amino-acids-for-hair-regrowth-you-should-know': {
      id: '/blogs/health-wellness-posts/7-amazing-amino-acids-for-hair-regrowth-you-should-know'
      path: '/blogs/health-wellness-posts/7-amazing-amino-acids-for-hair-regrowth-you-should-know'
      fullPath: '/blogs/health-wellness-posts/7-amazing-amino-acids-for-hair-regrowth-you-should-know'
      preLoaderRoute: typeof BlogsHealthWellnessPosts7AmazingAminoAcidsForHairRegrowthYouShouldKnowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/health-wellness-posts/magnesium-for-hair-growth': {
      id: '/blogs/health-wellness-posts/magnesium-for-hair-growth'
      path: '/blogs/health-wellness-posts/magnesium-for-hair-growth'
      fullPath: '/blogs/health-wellness-posts/magnesium-for-hair-growth'
      preLoaderRoute: typeof BlogsHealthWellnessPostsMagnesiumForHairGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/health-wellness-posts/magnesium-hair-growth': {
      id: '/blogs/health-wellness-posts/magnesium-hair-growth'
      path: '/blogs/health-wellness-posts/magnesium-hair-growth'
      fullPath: '/blogs/health-wellness-posts/magnesium-hair-growth'
      preLoaderRoute: typeof BlogsHealthWellnessPostsMagnesiumHairGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/health-wellness-posts/unlocking-the-secret-to-radiance-l-lysine-benefits-for-skin-before-and-after': {
      id: '/blogs/health-wellness-posts/unlocking-the-secret-to-radiance-l-lysine-benefits-for-skin-before-and-after'
      path: '/blogs/health-wellness-posts/unlocking-the-secret-to-radiance-l-lysine-benefits-for-skin-before-and-after'
      fullPath: '/blogs/health-wellness-posts/unlocking-the-secret-to-radiance-l-lysine-benefits-for-skin-before-and-after'
      preLoaderRoute: typeof BlogsHealthWellnessPostsUnlockingTheSecretToRadianceLLysineBenefitsForSkinBeforeAndAfterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/site-image/$': {
      id: '/api/public/site-image/$'
      path: '/api/public/site-image/$'
      fullPath: '/api/public/site-image/$'
      preLoaderRoute: typeof ApiPublicSiteImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AlopeciaAreataDoctorAtlantaRoute: AlopeciaAreataDoctorAtlantaRoute,
  AuthRoute: AuthRoute,
  BlackTrichologistAtlantaRoute: BlackTrichologistAtlantaRoute,
  BookRoute: BookRoute,
  CccaTreatmentAtlantaRoute: CccaTreatmentAtlantaRoute,
  ContactRoute: ContactRoute,
  EditorialPolicyRoute: EditorialPolicyRoute,
  FaqRoute: FaqRoute,
  FunctionalMedicineRoute: FunctionalMedicineRoute,
  HairDoctorAtlantaRoute: HairDoctorAtlantaRoute,
  HairLossTreatmentAtlantaRoute: HairLossTreatmentAtlantaRoute,
  HairRestorationSandySpringsRoute: HairRestorationSandySpringsRoute,
  LandingRoute: LandingRoute,
  Landing2Route: Landing2Route,
  LlmsDottxtRoute: LlmsDottxtRoute,
  MedicalReviewPolicyRoute: MedicalReviewPolicyRoute,
  PoliciesRoute: PoliciesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PrpHairTreatmentAtlantaRoute: PrpHairTreatmentAtlantaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TractionAlopeciaTreatmentAtlantaRoute: TractionAlopeciaTreatmentAtlantaRoute,
  TrichologyRoute: TrichologyRoute,
  VideosRoute: VideosRoute,
  BlogSegmentRoute: BlogSegmentRoute,
  ConcernsSlugRoute: ConcernsSlugRoute,
  TreatmentsSlugRoute: TreatmentsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ConcernsIndexRoute: ConcernsIndexRoute,
  TreatmentsIndexRoute: TreatmentsIndexRoute,
  BlogsHairLossHairLossAndPotassiumDeficiencyWhatSTheRelationshipRoute:
    BlogsHairLossHairLossAndPotassiumDeficiencyWhatSTheRelationshipRoute,
  BlogsHairLossHairLossEpidemicAmongBlackWomenRoute:
    BlogsHairLossHairLossEpidemicAmongBlackWomenRoute,
  BlogsHairLossHowToStopAlopeciaAreataFromGettingWorseRoute:
    BlogsHairLossHowToStopAlopeciaAreataFromGettingWorseRoute,
  BlogsHairLossHowToStopAlopeciaAreataFromSpreadingRoute:
    BlogsHairLossHowToStopAlopeciaAreataFromSpreadingRoute,
  BlogsHairLossMinoxidilItchyScalpKnowTheSurprisingFactsRoute:
    BlogsHairLossMinoxidilItchyScalpKnowTheSurprisingFactsRoute,
  BlogsHairLossStopHairLossWithDhtBlockersRoute:
    BlogsHairLossStopHairLossWithDhtBlockersRoute,
  BlogsHairLossThingsToDoBeforeYouGoogleTrichologistNearMeRoute:
    BlogsHairLossThingsToDoBeforeYouGoogleTrichologistNearMeRoute,
  BlogsHairLossTractionAlopeciaWhenIsItTooLateRoute:
    BlogsHairLossTractionAlopeciaWhenIsItTooLateRoute,
  BlogsHairLossTrichologistForBlackHairRoute:
    BlogsHairLossTrichologistForBlackHairRoute,
  BlogsHealthWellnessPosts7AmazingAminoAcidsForHairRegrowthYouShouldKnowRoute:
    BlogsHealthWellnessPosts7AmazingAminoAcidsForHairRegrowthYouShouldKnowRoute,
  BlogsHealthWellnessPostsMagnesiumForHairGrowthRoute:
    BlogsHealthWellnessPostsMagnesiumForHairGrowthRoute,
  BlogsHealthWellnessPostsMagnesiumHairGrowthRoute:
    BlogsHealthWellnessPostsMagnesiumHairGrowthRoute,
  BlogsHealthWellnessPostsUnlockingTheSecretToRadianceLLysineBenefitsForSkinBeforeAndAfterRoute:
    BlogsHealthWellnessPostsUnlockingTheSecretToRadianceLLysineBenefitsForSkinBeforeAndAfterRoute,
  ApiPublicSiteImageSplatRoute: ApiPublicSiteImageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
